name: Actions Workflow

on: 
  #push:
  # schedule:
  #   - cron: "*/5 * * * *"
  #   - cron: "*/6 * * * *"
  push: # This means push will only run when we push to master, OR any feature/ branch 
    branches:
      - "main"
      - 'feature/*' # won't match something like feature/a/anything
      - 'feature/**' # Will match feature/ branch or feature/a/anything
      - '!feature/featC' ## featC is ignored, MUST BE AFTER THE ALLOW
    tags: # there is alsow tags ignore
      - v1.*
    # paths: ## THis will only match java scripts repos, there is also paths-ignore
    #   - '**.js'
    #   - '!filename.js'
    paths-ignore: ## Ignore any push to the below directory
      - 'docs/**'
    #####
    ##### branches-ignore to ignore branches, but it can't be used if branches: is being used
    #####
    # branches-ignore:
    #  - "main"
  pull_request:
    types: [closed, assigned, opened, reopened]
  repository_dispatch:
    types: [mustafa-buildmmm]
jobs:
  run-github-actions-example:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List files ## to check the working directory,## $GITHUB_SHA will provide the commit ID,  
          ### $GITHUB_REPOSITORY includes the reponame (username/repo)
        run: |
          pwd
          ls -ltrh
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
        ## ls will show no files as github actions by default won't clone the repo, to do so we need the checkout action
        ## we can do something like git clone git@github:$GITHUB_REPOSITORY >> will have to add the ${{ github.token }} 
        ## then git checkout $GITHUB_SHA 
        ## or use the Checkout action as below
      - name: Checkout
        uses: actions/checkout@v2.3.4 ## this will authinticate and fetch the code

      - name: List files After checkout ## to check the working directory
        run: |
          pwd
          ls -ltrh
  
      - name: Simple JS Actions
        id: greet ## thisis needed to access the output in step2 (log greeting time)
        uses: actions/hello-world-javascript-action@v1 #We didn't use run as it is using an exiting action (repo:https://github.com/actions/hello-world-javascript-action branch: master )
        ## or can be actions/hello-world-javascript-action@master to refrence the master branch instead of a release
        ## can also be @commit-id
        with: # this is how to provide inputs to the action, check the rpo for the required inputs
          who-to-greet: Mustafa
      - name: log Greeting time using the output of the action # check the repo
        run: echo "${{ steps.greet.outputs.time }}"